import { getSession } from "next-auth/react";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Layout from "../components/Layout";
import Sidebar from "../components/Sidebar";
import NewFeed from "../components/NewFeed";
import Wigdet from "../components/Widget";
import { connectToDatabase } from "../utils/mongose";
export default function Home({ posts, users }) {
  const { status } = useSession();

  if (status === "loading") {
    return "Loading or not authenticated...";
  }
  return (
    <div className="bg-slate-100 min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main className="flex justify-center mt-20 mx-auto gap-x-4 ">
          <Sidebar className="flex-1" />
          <NewFeed className="flex-[2]" posts={posts} />
          <Wigdet className="flex-1" users={users}/>
        </main>
      </Layout>
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  // check user
  if (!session) {
    return {
      redirect: {
        permanent: false,
        destination: "/signin",
      },
    };
  }

  // Get Post in SSR
  const { db } = await connectToDatabase();
  const posts = await db
    .collection("posts")
    .find()
    .sort({ timestamp: -1 })
    .toArray();

    // Get Users in SSR
    const users = await db
    .collection("users")
    .find()
    .toArray();
  return {
    props: {
      session,
      posts: JSON.parse(JSON.stringify(posts)),
      users: JSON.parse(JSON.stringify(users))
    },
  };
}
